Repository brazil-data-cube/bdc-stac, pull requests merged in 2020-08, with the labels that each got.

#61 isolate environment variables
  DEPLOY.rst
  INSTALL.rst
  bdc_stac/__init__.py
  bdc_stac/config.py
  bdc_stac/data.py
  bdc_stac/routes.py
Labels: enhancement

#64 list private collections by token
  bdc_stac/__init__.py
  bdc_stac/config.py
  bdc_stac/data.py
  bdc_stac/routes.py
  setup.py
Labels: enhancement

#67 Hotfix/links
  bdc_stac/routes.py
  requirements.txt
Labels: enhancement

#70 Close #66 and fix links if access_token exists
  bdc_stac/data.py
  bdc_stac/routes.py
Labels: bug, enhancement

#95 Several reviews for releasing version 0.9.0
  .dockerignore
  .gitignore
  .readthedocs.yml
  .travis.yml
  CHANGES.rst
  DEPLOY.rst
  Dockerfile
  INSTALL.rst
  LICENSE
  MANIFEST.in
  Makefile
  README.rst
  bdc_stac/config.py
  bdc_stac/data.py
  bdc_stac/routes.py
  build.sh
  docs/sphinx/Makefile
  docs/sphinx/api.rst
  docs/sphinx/conf.py
  docs/sphinx/configurations.rst
  docs/sphinx/deploy.rst
  docs/sphinx/index.rst
  docs/sphinx/installation.rst
  docs/sphinx/license.rst
  pytest.ini
  run-tests.sh
  setup.cfg
  setup.py
Labels: enhancement, release

#97 fix build to deploy with docker
  .dockerignore
  Dockerfile
  bdc_stac/config.py
  build.sh
  setup.py
Labels: bug

#98 update requirements.txt and add tag in dependencies
  build.sh
  requirements.txt
  setup.py
Labels: bug
