Repository brazil-data-cube/bdc-stac, pull requests merged in 2020-09, with the labels that each got.

#102 Release 0.9.0 1
  CHANGES.rst
  README.rst
  bdc_stac/data.py
  bdc_stac/version.py
  docs/sphinx/index.rst
  setup.py
  tests/bdc_stac_tests/test_app.py
Labels: release

#108 Merge v0.9.0-3 into master
  CHANGES.rst
  README.rst
  bdc_stac/data.py
  bdc_stac/routes.py
  bdc_stac/version.py
  docs/sphinx/index.rst
  setup.py
  tests/bdc_stac_tests/test_app.py
Labels: enhancement

#110 Fix links
  bdc_stac/routes.py
Labels: bug
